### PR TITLE
Closing Issues

### PR DESCRIPTION
**Pull request by jhh3000**
Closing Issue #5

### CODE REVIEW

**Comment by jhh3000** [comment]
Also closed issues #6 and #7

**Comment by jhh3000** [comment]
Kyle updated the master repo with a few commits to test. I merged them in.

**Comment by jhh3000** [comment]
Closed issues: #9 and #10

**Comment by jhh3000** [comment]
Oops meant to merge and not close. Done.

**Comment by thebiglq12345** [comment]
Changed title workding so wafffle.io matches pull request with issues like others (hopefully).

**Pull request merged**
